### ISSUE TITLE
Bad error message on late submission

### ISSUE THREAD

**Issue by knrafto** [Cal-CS-61A-Staff/ok#1033]
We just show "Unauthorized" on the client. Not sure if it's a client or server issue (I'm guessing the latter)

```
Not capturing exception due to filters: <class 'werkzeug.exceptions.Forbidden'> (/usr/local/lib/python3.5/site-packages/raven/base.py:602, in capture)
Traceback (most recent call last):
  File "/code/server/controllers/api.py", line 519, in post
    backup = self.schema.store_backup(user)
  File "/code/server/controllers/api.py", line 378, in store_backup
    raise ValueError('Late Submission of {}'.format(args['assignment']))
ValueError: Late Submission of cal/cs61a/fa16/lab00

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/code/server/controllers/api.py", line 143, in wrapper
    return func(*args, **kwargs)
  File "/code/server/controllers/api.py", line 101, in wrapper
    return func(*args, **kwargs)
  File "/code/server/controllers/api.py", line 131, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/flask_restful/__init__.py", line 679, in wrapper
    resp = f(*args, **kwargs)
  File "/code/server/controllers/api.py", line 524, in post
    return restful.abort(403, message=str(e), data=data)
  File "/usr/local/lib/python3.5/site-packages/flask_restful/__init__.py", line 31, in abort
    original_flask_abort(http_status_code)
  File "/usr/local/lib/python3.5/site-packages/werkzeug/exceptions.py", line 646, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.Forbidden: 403: Forbidden
```

**Comment by knrafto** [comment]
I think the error message still appears, and the `Forbidden` was due to the oauth provider change.
