### ISSUE TITLE
Composition/FinalSubmission Broken on Master

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok#434]
The following traceback occurs on master when trying to view a diff. This may actually show up in other places too. 

The master branch hasn't been deployed - so we're okay for now.

```
Traceback (most recent call last):
  File "/Users/sumukh/Dropbox/CS61A/ok/server/app/urls.py", line 201, in api_wrapper
    rval = view(*args, **kwds)
  File "/Users/sumukh/Dropbox/CS61A/ok/server/gaenv/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/sumukh/Dropbox/CS61A/ok/server/app/api.py", line 226, in dispatch_request
    is_index=(method_name == 'index'))
  File "/Users/sumukh/Dropbox/CS61A/ok/server/app/api.py", line 204, in call_method
    return method(user, data)
  File "/Users/sumukh/Dropbox/CS61A/ok/server/app/api.py", line 364, in index
    result = self.model.can(user, need, query=query)
  File "/Users/sumukh/Dropbox/CS61A/ok/server/app/models.py", line 118, in can
    return cls._can(user, need, obj, query)
  File "/Users/sumukh/Dropbox/CS61A/ok/server/app/models.py", line 1169, in _can
    user, need, final.submission.get() if final else None, query)
  File "/Users/sumukh/Dropbox/CS61A/ok/server/app/models.py", line 768, in _can
    return Backup._can(user, need, submission.backup.get(), query)
AttributeError: 'NoneType' object has no attribute 'backup'
```

**Comment by Sumukh** [comment]
For reference - if you want to go back to when it's in a working state - this commit https://github.com/Cal-CS-61A-Staff/ok/commit/77d0a7a29533d9212a535525fbc6394193737dce is the most recently deployed.

**Comment by moowiz** [comment]
Ill look at this today. Thanks Sumukh

**Comment by moowiz** [comment]
Wait, do I need to fix this? It looks like it's fixed in the PR @alvinwan is doing...

**Comment by Sumukh** [comment]
@moowiz - That's only fixed because @alvinwan reset back to the commit that works. We basically can't use the most recent commit because some broke between 77d0a7a29533d9212a535525fbc6394193737dce and the most recent commit on master.
