### ISSUE TITLE
Score export results in DeadlineExceededError

### ISSUE THREAD

**Issue by albert12132** [Cal-CS-61A-Staff/ok#528]
After clicking the `Score` download button from the admin assignments view, I get this page (after a long waiting time):

```
User is [...].

Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 268, in Handle
    for chunk in result:
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/appstats/recording.py", line 1287, in appstats_wsgi_wrapper
    result = app(environ, appstats_start_response)
  File "/base/data/home/apps/s~ok-server/1.385471191882365125/gaenv/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/base/data/home/apps/s~ok-server/1.385471191882365125/gaenv/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/base/data/home/apps/s~ok-server/1.385471191882365125/gaenv/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/base/data/home/apps/s~ok-server/1.385471191882365125/gaenv/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/base/data/home/apps/s~ok-server/1.385471191882365125/app/urls.py", line 201, in api_wrapper
    rval = view(*args, **kwds)
  File "/base/data/home/apps/s~ok-server/1.385471191882365125/gaenv/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/base/data/home/apps/s~ok-server/1.385471191882365125/app/api.py", line 257, in dispatch_request
    instance=instance)
  File "/base/data/home/apps/s~ok-server/1.385471191882365125/app/api.py", line 206, in call_method
    return method(instance, user, data)
  File "/base/data/home/apps/s~ok-server/1.385471191882365125/app/api.py", line 850, in download_scores
    course_name, content = self.data_for_scores(obj, user)
  File "/base/data/home/apps/s~ok-server/1.385471191882365125/app/api.py", line 868, in data_for_scores
    content.extend(self.scores_for_student_or_group(student, obj)[0])
  File "/base/data/home/apps/s~ok-server/1.385471191882365125/app/api.py", line 883, in scores_for_student_or_group
    fs = models.User.get_final_submission(student, assignment.key)
  File "/base/data/home/apps/s~ok-server/1.385471191882365125/app/models.py", line 181, in get_final_submission
    FinalSubmission.submitter==self.key).get()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/query.py", line 1222, in get
    return self.get_async(**q_options).get_result()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 326, in get_result
    self.check_success()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 321, in check_success
    self.wait()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 305, in wait
    if not ev.run1():
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/eventloop.py", line 235, in run1
    delay = self.run0()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/eventloop.py", line 197, in run0
    callback(*args, **kwds)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 375, in _help_tasklet_along
    ns = namespace_manager.get_namespace()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/namespace_manager/namespace_manager.py", line 86, in get_namespace
    name = os.environ.get(_ENV_CURRENT_NAMESPACE, None)
DeadlineExceededError
```

**Comment by LuiseV** [comment]
Yes, @Sumukh mentioned this in #484. I'm currently trying to fix it by making the export a deferred task and writing it to Google Cloud Storage.
