### ISSUE TITLE
Problem downloading projects

### ISSUE THREAD

**Issue by jeffreylu017** [Cal-CS-61A-Staff/ok#541]
When I try to to export grades for project, I get an error as I'm downloading:
```
~/workspace/cs61a/grading/hog$ python3 ok --export --latest
=====================================================================
Assignment: Project 1: Hog
OK, version v1.3.35
=====================================================================

545 submissions left to download.
    [omitted]
Checking for software updates...
OK is up to date
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "ok/__main__.py", line 9, in <module>
  File "ok/client/cli/ok.py", line 121, in main
  File "ok/client/protocols/export.py", line 54, in run
  File "ok/client/protocols/export.py", line 73, in download_submission
  File "ok/client/protocols/export.py", line 124, in get_latest_submission
KeyError: 'messages'
```
When I check submissions, I see that I've only downloaded ~20 submissions.

For some reason this only happens for projects.  I'm able to download homework and labs just fine.

Also as a note, I'm using a custom version of OK at the moment modified by @albert12132 , since v1.3.35 has a bug where downloading submissions might timeout.  But it probably isn't causing this.

**Comment by albert12132** [comment]
This is an ok-client bug. I'll move it there.
