### ISSUE TITLE
Error on user api

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok#570]
/api/v1/user/studentemail@gmail.com?course=&format=json
      BadRequestError: Key path element must not be incomplete: [Coursev2: ]

```

    E 09:08:57.553 Key path element must not be incomplete: [Coursev2: ]
      Traceback (most recent call last):
        File "/base/data/home/apps/s~ok-server/1.386281465084271028/app/urls.py", line 201, in api_wrapper
          rval = view(*args, **kwds)
        File "/base/data/home/apps/s~ok-server/1.386281465084271028/gaenv/flask/views.py", line 84, in view
          return self.dispatch_request(*args, **kwargs)
        File "/base/data/home/apps/s~ok-server/1.386281465084271028/app/api.py", line 247, in dispatch_request
          instance=instance)
        File "/base/data/home/apps/s~ok-server/1.386281465084271028/app/api.py", line 206, in call_method
          return method(instance, user, data)
        File "/base/data/home/apps/s~ok-server/1.386281465084271028/app/api.py", line 549, in get
          return obj.get_course_info(data['course'].get())
        File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/key.py", line 557, in get
          return self.get_async(**ctx_options).get_result()
        File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 326, in get_result
          self.check_success()
        File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 369, in _help_tasklet_along
          value = gen.throw(exc.__class__, exc, tb)
        File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/context.py", line 744, in get
          entity = yield self._get_batcher.add_once(key, options)
        File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 369, in _help_tasklet_along
          value = gen.throw(exc.__class__, exc, tb)
        File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/context.py", line 329, in _get_tasklet
          entities = yield self._conn.async_get(options, datastore_keys)
        File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 455, in _on_rpc_completion
          result = rpc.get_result()
        File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 613, in get_result
          return self.__get_result_hook(self)
        File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/datastore/datastore_rpc.py", line 1650, in __get_hook
          self.check_rpc_success(rpc)
        File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/datastore/datastore_rpc.py", line 1373, in check_rpc_success
          raise _ToDatastoreError(err)
      BadRequestError: Key path element must not be incomplete: [Coursev2: ]
    I 09:08:57.570 Saved; key: __appstats__:037400, part: 165 bytes, full: 47625 bytes, overhead: 0.002 + 0.004; link: http://ok-server.appspot.com/_ah/stats/details?time=1439482137480
```

**Comment by alvinwan** [comment]
It looks like the course key is missing from the API call. Where was this call made?

**Comment by Sumukh** [comment]
I'm not sure. I wanted to post this up so that we investigate the source.

**Comment by alvinwan** [comment]
Mhm, gotcha. I'll investigate. Looks like a front-end issue?

**Comment by Sumukh** [comment]
I see this a lot more frequently. I'm guessing it's a front-end issue - if not could it be an issue with the not enrolled page?

**Comment by alvinwan** [comment]
Possibly. Since we're seeing a spike now, it seems highly likely.

**Comment by Sumukh** [comment]
I just replicated it - you have to hit the backup button when from the backup code view. The alert then shows up and presents us with the course selection page.

**Comment by knrafto** [comment]
v2 is no longer being maintained.
