### ISSUE TITLE
Submission Export Encoding Error

### ISSUE THREAD

**Issue by Sumukh** [Cal-CS-61A-Staff/ok#597]
I tried to export submissions for the other course using ok and keep getting (a variety) of errors. 

```
    E 18:51:22.586 'ascii' codec can't encode character u'\u2212' in position 4614: ordinal not in range(128)
      Traceback (most recent call last):
        File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
          rv = self.handle_exception(request, response, e)
        File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
          rv = self.router.dispatch(request, response)
        File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
          return route.handler_adapter(request, response)
        File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
          return handler.dispatch()
        File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
          return self.handle_exception(e, self.app.debug)
        File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
          return method(*args, **kwargs)
        File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 310, in post
          self.run_from_request()
        File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 305, in run_from_request
          run(self.request.body)
        File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 147, in run
          return func(*args, **kwds)
        File "/base/data/home/apps/s~ok-server/1.387324334233159580/app/utils.py", line 615, in subms_to_gcs
          zipfile = add_subm_to_zip(subm, Submission, zipfile, result)
        File "/base/data/home/apps/s~ok-server/1.387324334233159580/app/utils.py", line 560, in add_subm_to_zip
          return add_to_zip(zipfile, file_contents, name)
        File "/base/data/home/apps/s~ok-server/1.387324334233159580/app/utils.py", line 122, in add_to_zip
          zipfile.writestr(join(dir, filename), contents)
        File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/zipfile.py", line 1220, in writestr
          zinfo.CRC = crc32(bytes) & 0xffffffff       # CRC-32 checksum
      UnicodeEncodeError: 'ascii' codec can't encode character u'\u2212' in position 4614: ordinal not in range(128)
    I 18:51:24.083 Full proto way too large to save, cleared frames.
```

**Comment by Sumukh** [comment]
Ok - I think I fixed that with some encodes - but the download all for a course is taking a while (> 10 minutes)

**Comment by knrafto** [comment]
The server is serializing the (quite large) zipfile to a string and OOMs. Instead of holding it all in memory, we should stream it over to object storage, probably using https://github.com/allanlei/python-zipstream. I'll take a stab at this
